language: php

matrix:
  include:
    - php: 5.6
      env:
        - PHPCS_TEST=1
    - php: 7.2
    - php: hhvm

before_script:
  - if [[ $PHPCS_TEST ]]; then composer global require squizlabs/php_codesniffer:^3 --prefer-dist --no-interaction --no-progress --no-suggest -o; fi
  - composer install -n --dev --prefer-source

script: 
  - if [[ $PHPCS_TEST ]]; then phpcs --standard=PSR2 ./src; fi
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
